"""add unique constraint to notifications table

Revision ID: 2041a01fad2e
Revises: c04975481b37
Create Date: 2026-02-17 09:04:20.788478

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2041a01fad2e"
down_revision: Union[str, Sequence[str], None] = "c04975481b37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DELETE FROM notifications n1
    USING notifications n2
    WHERE n1.id > n2.id
      AND n1.receiver_id = n2.receiver_id
      AND n1.actor_id = n2.actor_id
      AND n1.type = n2.type
      AND n1.post_id = n2.post_id
      AND n1.comment_id = n2.comment_id
    """)
    op.create_unique_constraint(
        "uq_notification_action",
        "notifications",
        ["receiver_id", "actor_id", "type", "post_id", "comment_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_notification_action", "notifications", type_="unique")
    # ### end Alembic commands ###
