"""init Tags and Post Tags table for multi tagged post

Revision ID: 32d46d03d69a
Revises: c0e4fd1029cd
Create Date: 2026-02-10 10:45:39.934334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d46d03d69a'
down_revision: Union[str, Sequence[str], None] = 'c0e4fd1029cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.add_column('posts', sa.Column('tags', sa.String(), nullable=False))
    op.drop_index(op.f('ix_posts_topic'), table_name='posts')
    op.create_index(op.f('ix_posts_tags'), 'posts', ['tags'], unique=False)
    op.drop_column('posts', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_posts_tags'), table_name='posts')
    op.create_index(op.f('ix_posts_topic'), 'posts', ['topic'], unique=False)
    op.drop_column('posts', 'tags')
    op.drop_table('post_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
