"""init user table

Revision ID: 66086affc8f3
Revises: 
Create Date: 2026-02-09 21:20:11.991695

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '66086affc8f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
