"""remove tag column from post

Revision ID: 78b9ec308740
Revises: 32d46d03d69a
Create Date: 2026-02-10 10:46:20.410304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b9ec308740'
down_revision: Union[str, Sequence[str], None] = '32d46d03d69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_tags'), table_name='posts')
    op.drop_column('posts', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_posts_tags'), 'posts', ['tags'], unique=False)
    # ### end Alembic commands ###
