"""remove enum dismissed from reports

Revision ID: dfe11258ac47
Revises: 444fbf2f65a1
Create Date: 2026-02-14 20:24:00.264079

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dfe11258ac47"
down_revision: Union[str, Sequence[str], None] = "444fbf2f65a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_comment_like", "comment_likes", ["user_id", "comment_id"]
    )
    op.drop_constraint(
        op.f("comment_mentions_post_id_fkey"), "comment_mentions", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("comment_mentions_user_id_fkey"), "comment_mentions", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("comment_mentions_comment_id_fkey"), "comment_mentions", type_="foreignkey"
    )
    op.create_foreign_key(None, "comment_mentions", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "comment_mentions", "comments", ["comment_id"], ["id"])
    op.create_foreign_key(None, "comment_mentions", "posts", ["post_id"], ["id"])
    op.create_unique_constraint(
        "unique_post_like", "post_likes", ["user_id", "post_id"]
    )
    op.drop_constraint(
        op.f("post_mentions_post_id_fkey"), "post_mentions", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("post_mentions_user_id_fkey"), "post_mentions", type_="foreignkey"
    )
    op.create_foreign_key(None, "post_mentions", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "post_mentions", "posts", ["post_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "post_mentions", type_="foreignkey")
    op.drop_constraint(None, "post_mentions", type_="foreignkey")
    op.create_foreign_key(
        op.f("post_mentions_user_id_fkey"),
        "post_mentions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("post_mentions_post_id_fkey"),
        "post_mentions",
        "posts",
        ["post_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("unique_post_like", "post_likes", type_="unique")
    op.drop_constraint(None, "comment_mentions", type_="foreignkey")
    op.drop_constraint(None, "comment_mentions", type_="foreignkey")
    op.drop_constraint(None, "comment_mentions", type_="foreignkey")
    op.create_foreign_key(
        op.f("comment_mentions_comment_id_fkey"),
        "comment_mentions",
        "comments",
        ["comment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("comment_mentions_user_id_fkey"),
        "comment_mentions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("comment_mentions_post_id_fkey"),
        "comment_mentions",
        "posts",
        ["post_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("unique_comment_like", "comment_likes", type_="unique")
    # ### end Alembic commands ###
